name: Run Python Script

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar
  pull_request:
    branches:
      - main  # ou a branch que você deseja monitorar
env:
  client_id: ${{ secrets.CLIENTE_ID_DOMO }}
  client_secret: ${{ secrets.SECRET_DOMO }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12  # ou a versão que você está usando

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Geckodriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar
        GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep 'tag_name' | cut -d\" -f4)
        wget "https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz"
        tar -xvzf "geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz"
        sudo mv geckodriver /usr/local/bin/

    - name: Run tests
      run: |
        python scraper.py
      env:
        DISPLAY: ":99.0"
